version: '2.1'

services:
  teonite-task-frontend:
    image: teonite-task-frontend
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    ## set your startup file here
    command: node --inspect index.js